{
 "title": "Pizza Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_SUCCESS{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_FAIL{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_MEMORY{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "cpu_CPU{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "AuthRouter Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(latency_register{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Register"
    },
    {
     "expr": "rate(latency_login{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Login"
    },
    {
     "expr": "rate(latency_logout{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Logout"
    },
    {
     "expr": "rate(latency_updateUser{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Update user"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(pizza_PURCHASES{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "pizza_FAILURES{source=\"jwt-pizza-service\"}",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_REVENUE{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "OrderRouter Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(latency_createOrder{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Create order"
    },
    {
     "expr": "rate(latency_getOrders{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get orders"
    },
    {
     "expr": "rate(latency_getMenu{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get menu"
    },
    {
     "expr": "rate(latency_addMenuItem{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Add menu item"
    },
    {
     "expr": "rate(latency_pizzaCreation{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza creation"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(request_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(request_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(request_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(request_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "users_ACTIVE{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "FranchiseRouter Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(latency_createFranchise{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Create franchise"
    },
    {
     "expr": "rate(latency_createStore{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Create store"
    },
    {
     "expr": "rate(latency_getFranchises{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get franchises"
    },
    {
     "expr": "rate(latency_getUserFranchises{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Get user's franchises"
    },
    {
     "expr": "rate(latency_deleteFranchise{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Delete franchise"
    },
    {
     "expr": "rate(latency_deleteStore{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Delete store"
    }
   ]
  }
 ]
}